blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/CJFWeatherhead/ChatrixCD/security/advisories/new
    about: Please report security vulnerabilities through GitHub's private vulnerability reporting feature
  - name: Question or Discussion
    url: https://github.com/CJFWeatherhead/ChatrixCD/discussions
    about: Ask questions and discuss ideas with the community
