name: Feature Request
description: Suggest an idea for ChatrixCD
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you have in mind
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        1. User sends command...
        2. Bot responds with...
        3. System does...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Have you thought of any other ways to solve this problem?
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of ChatrixCD does this feature relate to?
      options:
        - Bot Commands
        - Matrix Integration
        - Semaphore Integration
        - Authentication
        - Configuration
        - Security
        - Deployment/Operations
        - Documentation
        - Testing
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the bot
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a real-world scenario where this feature would be useful
      placeholder: |
        In my team's workflow, we...
        This feature would help us by...
    validations:
      required: false

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Show how you would use this feature (commands, configuration, etc.)
      placeholder: |
        !cd schedule "0 0 * * *" deploy production
        
        Or in config.json:
        ```json
        {
          "scheduling": {
            "enabled": true
          }
        }
        ```
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to submit a pull request to implement this feature
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information that might help
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for similar feature requests and didn't find any duplicates
          required: true
        - label: This feature aligns with the project's goals and scope
          required: false
